version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: mern_template_server
    container_name: mern_template_server
    ports:
      - 5000:5000
    volumes:
      - ./server:/index.js
      - /app/node_modules
    env_file: ./server/.env
